# deployment/kube-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: artist-srv
  namespace: dev-01
  labels:
    name: artist
spec:
  type: NodePort
  ports:
    - name: artist
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: artist
# $ kubectl apply -f kube-service.yaml
# service/artist-srv created

# service name: artist-srv
# website:  http://localhost:30080
