apiVersion: v1
kind: Pod
metadata:
  name: artist-demo
  namespace: dev-01
spec:
  containers:
    - name: artist-demo
      image: yinglu91/artist:1.0
      resources:
        limits:
          memory: '200Mi'
        requests:
          memory: '100Mi'
