apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: artist-replicaset
  namespace: dev-01
  labels:
    name: artist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artist
  template:
    metadata:
      name: artist-pot
      labels:
        app: artist
    spec:
      containers:
        - name: artist
          image: yinglu91/artist:1.0
          ports:
            - containerPort: 80
# $ kubectl apply -f kube-replicaset.yaml
# replicaset.apps/artist-replicaset created

# replicaSet name: artist-replicaset
# pot name:        artist-replicaset-gqpx5
