apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: artist-replicaset
  namespace: dev-01
  labels:
    name: artist
spec:
  replicas: 3
  selector:
    matchLabels:
      app: artist
  template:
    metadata:
      labels:
        app: artist
    spec:
      containers:
        - name: artist
          image: yinglu91/artist:1.0
          ports:
            - containerPort: 80
